### PR TITLE
Allow syncing values through passing in {values: true} to options

### PR DESCRIPTION
**Pull request by ajoslin**

### CODE REVIEW

**Comment by bendrucker** [comment]
Just curious, what's your intended use case here? I originally built this to manage view state for changing lists. The easiest example is the product cards on eazeup.com. If you switch menus your state (prices selected, descriptions expanded, etc.) is discarded automatically because those product IDs leave the array.

This package is almost a dupe of [observ-store](https://github.com/bendrucker/observ-store) but observ-store leaks data by design and retains everything you put in it even when the ID leaves the array. I was thinking of consolidating and having observ-sync-hash end up powering observ-store.

The real challenge would be to make the updates atomic here instead of one-write-per-record.

**Comment by ajoslin** [comment]
I'm not worried about perf for now, but doing a transaction would of course be desirable.

My use-case is a component has an ordered list of items, and I store the id of the one that is 'currently selected' in that list of items.

Other components need to know which item that component has currently selected, and that means I either need a hash or a lot of `indexOf` lookups.

And yes, I thought of using observ-store and avoided it for the same reasons you said. observ-store would need major changes and I didn't know how supportive you would be of those.

I don't think it would be very to make it atomic, just get the plain-old-javascript hash out and mutate that then hash.set at the end.

Let me know if you want me to edit this PR to make it atomic.  I'm personally just not worried about those optimizations yet, but I will be worried about them later.

**Comment by bendrucker** [comment]
> I'm not worried about perf for now, but doing a transaction would of course be desirable.

Me neither. I'm more concerned with the learning curve around observables and how to decide between a [soft-set](https://github.com/bendrucker/soft-set) and ignoring dupes on read, e.g. via debounce or comparison. The latter makes it really easy to leak implementation details between parts of an app so I'm steering my packages towards deduping at write time.

This is fine for now as written. I'll take a stab at doing it via a single `set` sometime in the future.

**Comment by ajoslin** [comment]
Yes, I see the concern with deduping. I encounter it all the time too.

> I'm steering my packages towards deduping at write time.

This is definitely best, because it dedupes by default with no effort on the developer's part.

**Pull request merged**
